export const ActionTypes = {
    FETCH_POSTS: "FETCH_POSTS",
    FETCH_FOLLOWS: "FETCH_FOLLOWS",
    FETCH_POST: "FETCH_POST",
    ADD_LIKES: "ADD_LIKES",
    FETCH_MYPOSTS: "FETCH_MYPOSTS",
    SEARCH_STRING: "SEARCH_STRING",
    FETCH_SEARCHPOSTS: "FETCH_SEARCHPOSTS",
}