export const ActionTypes = {
    SET_POSTS: "SET_POSTS",
    SELECTED_POST: "SELECTED_POST",
    REMOVE_SELECTED_POST: "REMOVE_SELECTED_POST",
    SET_TOKEN: "SET_TOKEN",
    REMOVE_TOKEN: "REMOVE_TOKEN",
    SET_USER_NICKNAME: "SET_USER_NICKNAME",
    REMOVE_USER_NICKNAME: "REMOVE_USER_NICKNAME",
}